name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add server to known_hosts
        run: |
          ssh-keyscan ${{ secrets.SERVER_ADDRESS }} > ~/.ssh/known_hosts

      - name: Run deployment script
        env:
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV_FILE_PATH }}
          REPOSITORY: ${{ secrets.REPOSITORY }}
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SERVER_ADDRESS }} "bash -c '
            set -e

            if [ -d \"$APP_PATH/.git\" ]; then
              cd $APP_PATH
              git pull origin main
            else
              git clone $REPOSITORY $APP_PATH
              cd $APP_PATH
            fi

            composer install --no-dev --no-progress --prefer-dist

            if [ -n \"$PRODUCTION_ENV\" ]; then
              cp $PRODUCTION_ENV .env
            fi

            php artisan migrate --force
            php artisan db:seed --force

            php artisan config:cache
            php artisan route:cache
            php artisan view:cache
          '"
