name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed
          chmod 600 ~/.ssh/id_ed

          touch ~/.ssh/known_hosts

          ssh-keygen -f "/home/runner/.ssh/known_hosts" -R ${{ secrets.SERVER_ADDRESS }}

          ssh-keyscan -H ${{ secrets.SERVER_ADDRESS }} >> ~/.ssh/known_hosts

      - name: Run deployment script
        env:
          SERVER_ADDRESS: ${{ secrets.SERVER_ADDRESS }}
          SSH_USER: ${{ secrets.SSH_USER }}
          APP_PATH: ${{ secrets.APP_PATH }}
          PRODUCTION_ENV: ${{ secrets.PRODUCTION_ENV_FILE_PATH }}
        run: |
          ssh -i ~/.ssh/id_ed -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SERVER_ADDRESS }} 'bash -s' < ./.github/scripts/deploy.sh
